#!/bin/sh
#
# Installation script for knx2mqtt and its dependencies
#
# (c) Gerrit Beine, 2019-2022
#
 
python3 -m venv .

. bin/activate
pip install --upgrade pip
pip install -r requirements.txt
pip install -e knx2mqtt
